version: '3.8'

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: kvblog
      POSTGRES_PASSWORD: kvblogpw
      POSTGRES_DB: kvblogdb
    ports:
      - "55432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: kvblog.api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__KVBlogConnectionString=Host=db;Port=5432;Database=kvblogdb;Username=kvblog;Password=kvblogpw
    ports:
      - "8080:8080"
    depends_on:
      - db

  client:
    build:
      context: .
      dockerfile: kvblog.client.razor/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - KvblogBaseApiUrl=http://api:8080
    ports:
      - "8081:8081"
    depends_on:
      - api

volumes:
  pgdata: