version: '3.8'

services:
  caddy:
    image: caddy:latest
    container_name: kvblog-caddy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    networks:
      - kvblog_backend

networks:
  kvblog_backend:
    external: true