name: Deploy to Hetzner

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Run unit tests
        run: dotnet test Kvblog.sln --verbosity normal
                      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
           version: v0.11.2
        
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push API image
        uses: docker/build-push-action@v5
        with:
          context: .  # Use root directory as context
          file: ./kvblog.api/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/kvblog-api:latest

      - name: Build and push Client image
        uses: docker/build-push-action@v5
        with:
          context: . # Use root directory as context
          file: ./kvblog.client.razor/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/kvblog-client-razor:latest
          
      - name: Upload kvblog to Hetzner via SCP
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HETZNER_SERVER_IP }}
          username: root
          key: ${{ secrets.HETZNER_SSH_KEY }}
          source: "*"
          target: "/root/kvblog"

      - name: Create .env file on Hetzner
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HETZNER_SERVER_IP }}
          username: root
          key: ${{ secrets.HETZNER_SSH_KEY }}
          script: |
            cat <<EOF > /root/kvblog/.env
            AUTH0_KVBLOGCLIENTID=${{ secrets.AUTH0_KVBLOGCLIENTID }}
            AUTH0_KVBLOGCLIENTSECRET=${{ secrets.AUTH0_KVBLOGCLIENTSECRET }}
            AUTH0_KVBLOGDOMAIN=${{ secrets.AUTH0_KVBLOGDOMAIN }}
            AUTH0_KVBLOGAUDIENCE=${{ secrets.AUTH0_KVBLOGAUDIENCE }}
            AUTH0_KVBLOGAUTHORITY=${{ secrets.AUTH0_KVBLOGAUTHORITY }}
            AUTH0_KVBLOGAUTHURL=${{ secrets.AUTH0_KVBLOGAUTHURL }}
            EOF

      - name: Deploy to Hetzner
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HETZNER_SERVER_IP }}
          username: root
          key: ${{ secrets.HETZNER_SSH_KEY }}
          script: |
            cd kvblog
            docker compose -f docker-compose.prod.yml down
            docker compose -f docker-compose.prod.yml pull
            docker compose --env-file .env -f docker-compose.prod.yml up -d